server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_flea_market?serverTimezon=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#配置文件存储的默认路径
flea-market:
  path: E:\spring boot\flea_market\flea_market
