server:
  port: 8080

spring:
  application:
    name: cinema
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_cinema?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    expire: 120
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: cinema

ali-pay:
  appId:
  seller-id:
  gateway-url: https://openapi.alipaydev.com/gateway.do
  private-key:
  public-key:
  content-key:
  return-url: http://localhost:8081/#/user/order
  notify-url:


