/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ForgetPage: typeof import('./src/components/welcome/ForgetPage.vue')['default']
    LoginPage: typeof import('./src/components/welcome/LoginPage.vue')['default']
    RegisterPage: typeof import('./src/components/welcome/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
