server:
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    accept-count: 30000
    min-spare-threads: 20
    max-connections: 30000
#    key-alias: client

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  freemarker:
    check-template-location: false
  profiles:
    active: prod
#    active: test
    #active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: id_worker
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG



# sm.ms 图床的 token
smms:
  token: xx

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: xxx

jmshop:
  #通知相关配置
  notify:
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      # 如果是腾讯云短信，则设置active的值tencent
      # 如果是阿里云短信，则设置active的值aliyun
      active: aliyun
      sign: xxxx
      template:
        - name: paySucceed
          templateId: xxx
        - name: captcha
          templateId: xxx
        - name: ship
          templateId: xxx
        - name: refund
          templateId: xxx
      tencent:
        appid: 11
        appkey: 22
      aliyun:
        regionId: cn-hangzhou
        accessKeyId:
        accessKeySecret:


  # 快鸟物流查询配置
  express:
    enable: true
    appId: xxx
    appKey: xxx


#华为云OBS云存储
huaweicloud:
  obs:
    end_point: obs.cn-south-1.myhuaweicloud.com
    accessible_domain_name: https://xxx-mall.obs.cn-south-1.myhuaweicloud.com
    access_key_id: xxx
    secret_access_key: xxx
    bucket_name: xxxx-mall
    local_file_path: /www/wwwlogs
    cloud_file_path: mall/objservice

