#配置数据源
server:
  port: 8442
  http:
    port: 8009

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://xxxx:3306/xxxx?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: xxxx
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update
  redis:
    #数据库索引
    database: 14
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 10000

# 是否限制单用户登录
single:
  login: true

#jwt
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: xxxxx
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 604800000
  # 在线用户key
  online-key: m-online-token



#是否开启 swagger-ui
swagger:
  enabled: true
  title: jmshop商城移动端API
  serverUrl: http://localhost:8009
  version: 2.0

# 文件存储路径
file:
  path: D:\jmshop\file\
  avatar: D:\jmshop\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
  localUrl:


